### ISSUE TITLE
About metrics generation

### ISSUE THREAD

**Issue by onselakin** [compliance-framework/docs#6]
About the issue mentioned [here](https://github.com/compliance-framework/website/blob/main/sequence_diagrams/ASSESSMENT_RESULT_CONSUMER.md#:~:text=There%20is%20an%20issue%20here%20whjich%20is%20the%20cost%20to%20understand%20the%20scenario%20to%20properly%20create%20the%20metrics):

I'm considering leveraging an open-source (oss) database specifically for metrics collection and analytics, such as InfluxDB or Prometheus. My initial idea was to collect metrics in these databases while using the Assessment Result Collector, provide a simpler snapshot to MongoDB, such as failed jobs, successful attestations, etc. From there, the Dashboard API could run simple queries to offer critical data. 

If more detailed or drill-down-enabled analytics are needed, database-specific tools like Grafana or Chronograf could be used (though I'm not entirely sure about the latter).

**Comment by gusfcarvalho** [comment]
for me there is an issue with granularity here, that we've seen during the PoC. On the PoC, the metrics were produced at the Attestation Level - which is fine. However, from the attestation level, it was very hard to produce a view per Control or per Component, because we don't know how many attestations there are per assessment, or how many assessments per control (yes, we could just get it all and filter by labels, but then we lose the ability to see which assessment failed).

The question that I wanted to bring is, from a given raw metrics on the Job Spec, how would we keep track that a given Component is compliant/not-compliant ? Or that a Given assessment for a given control on a given component failed?


On the PoC, we "solved" this by having metrics generated from the raw metrics
```
Component -> generates from raw componentControl
ComponentControl -> generates from raw componentAssessment
ComponentAssessment -> generates from Raw componentAttestation
ComponentAttestation -> Actual raw metrics
```

**Comment by onselakin** [comment]
Can't we simply handle this by containing all the required data within the context that we pass to the Assessment Plugins by the Job Runner? We have the Assessment Runtime Id, Component Id, Assessment Id, and Assessment Action Id. Each plugin could generate metrics using all this data collectively, which would ultimately aid us in filtering or analysis.

**Comment by gusfcarvalho** [comment]
my trouble is that the `Assessment` metric is an AND operation on all of the `Assessment Actions` bound to it. From what I'm thinking, we will not have any insurance that all Assessment Actions of a given Assessment are ran by the same runtime. Same applies to Component, Control.

**Comment by gusfcarvalho** [comment]
the only way I can see how to solve this with our current approach after raw metrics are put on the metrics DB - either with custom queries on the metrics DB itself (which means we lose time scale on them), or a processing job iterating over the metrics DB.

**Comment by gusfcarvalho** [comment]
The only thing not covered with our current documentation is how would we generate "processed metrics" (i.e. consolidated information about a set of Observations, Attestations, Risks, Findings, etc.

This is covered in https://github.com/compliance-framework/docs/issues/22, so I'm closing this one.
