### ISSUE TITLE
General UUID assignment and usage

### ISSUE THREAD

**Issue by onselakin** [compliance-framework/docs#7]
[Assignment of UUIDs to Assessment Runtimes](https://chat.openai.com/#:~:text=Assessment%20Runtime%20Diagrams%20on%20GitHub):

Since installing runtimes requires some human intervention (even with IaC), why not let the UUIDs be configurable? We could allow the usage of friendly names or slugs, and have the Core assign UUIDs to runtimes based on these slugs, which could then be used for further API calls.

**Comment by gusfcarvalho** [comment]
imagine we have a runtime named `sassy`. When `sassy` asks for a UUID, it gets one. What happens if a given setup needs two `sassy` instances? Would they have the same UUID? If not, how would these two instances be able to know which one of them has which name?

UUID assignments by the control plane would allow multiple replicas of the same runtime to handle different workloads.

Note that the problem here is not the naming, we could still say these two instances belong to the `sassy` class - but ultimately I see benefit in having the control plane to assign a UUID to them.

I believe your idea is regarding this latter mode of having a class with UUIDs assigned to individual instances, right?

**Comment by onselakin** [comment]
> I believe your idea is regarding this latter mode of having a class with UUIDs assigned to individual instances, right?

Exactly. This makes it a lot easier for humans to understand things like what the runtime is doing, where it's running, etc., at first glance. Think of it as a logical grouping of runtimes.

**Comment by gusfcarvalho** [comment]
LGTM. What changes from a flow perspective? Almost nothing, right?
